config/routes.rb
RubyMnWebsite::Application.routes.draw do
  resources :users do
    get 'page/:page', :action => :index, :on => :collection

    member do
      get :login
    end

    new do
      get  :validate
      get  :forgot_password
      post :reset
      get  :change_password
      post :set_password
    end
  end

  resource :for_hire
  match '/for_hires' => 'for_hires#index', :as => :for_hires

  resources :events do
    member do
      delete :admdestroy
      #put    :approve
    end

    collection do
      get :user_index
    end
  end

  resources :openings do
    get 'page/:page', :action => :index, :on => :collection
  end
  resources :projects
  resource :session
  resources :sponsors

  # map.admin '/admin/:action/:id', :controller => 'admin'
  #match '/admin/:action/:id' => 'admin', :as => :admin

  put '/admin/events/:id/approve' => 'admin#approve', :as => :admin_approve_event
  match '/admin'        => 'admin#index',   :as => :admin_index

  root :to => 'welcome#index'
end

app/models/for_hire.rb
# == Schema Information
#
# Table name: for_hires
#
#  id      :integer          not null, primary key
#  blurb   :text             not null
#  email   :string(200)      default(""), not null
#  title   :string(200)      default(""), not null
#  user_id :integer
#

class ForHire < ActiveRecord::Base
  belongs_to :user

  validates :user_id, :presence => true
  validates :title,   :presence => true
  validates :email,   :presence => true
  validates :blurb,   :presence => true
end

app/controllers/for_hire_controller.rb
class ForHireController < ApplicationController
  before_filter :login_required, :except=>[:index]

  def index
    @for_hires = ForHire.find :all, :order=>'title'
  end

  def create
    if request.post? and params['for_hire']['id'].nil?
      if (fh = ForHire.new params['for_hire'])
        fh.user = current_user
        fh.save
        redirect_to :action=>'index'
      else
        render_text 'Error saving.'
      end
    elsif request.post? and !params['for_hire'][:id].nil?
      update 
    else
      render :action=>'for_hire_form'
    end
  end

  def destroy
    fh = ForHire.find(params[:id])
    if fh.user == current_user
      fh.destroy
      redirect_to :action=>'index'
    else
      session[:uid] = nil;
      redirect_to :controller=>'welcome', :action=>'index'
    end
  end


  def edit
    if !params[:id].nil?
      @for_hire=ForHire.find(params[:id])
      if  not (@for_hire.user == current_user)
        session[:uid] = nil
        redirect_to :controller=>'welcome', :action=>'index'
      else
        render :action=>'for_hire_form'
      end

    else
        render :action=>'for_hire_form'
    end

  end

  def update 
    fh = ForHire.find params['for_hire'][:id]
    if fh.user == session[:uid]
      if fh.update_attributes params['for_hire']
        redirect_to :action=>'index'
      else
        render_text 'Error Saving'
      end
    else
      session[:uid] = nil
      redirect_to :controller=>'welcome', :action=>'index'
    end

  end
end

app/controllers/for_hires_controller.rb
class ForHiresController < ApplicationController
  before_filter :login_required, :except => :index
  before_filter :bounce_foreign_access, :only => [:edit, :update, :destroy]

  def index
    @for_hires = ForHire.includes(:user).order('RANDOM()')
  end

  def new
    @for_hire = current_user.build_for_hire
  end

  def show
    redirect_to for_hires_path
  end

  def create
    @for_hire = current_user.build_for_hire(params[:for_hire])

    if @for_hire.save
      flash[:notice] = "Created for hire entry."
      redirect_to for_hires_path
    else
      flash.now[:alert] = "Error creating for hire profile."
      render :action => :new
    end
  end

  def edit
    @for_hire = current_user.for_hire
  end

  def update 
    @for_hire = current_user.for_hire
    if @for_hire && @for_hire.update_attributes(params[:for_hire])
      redirect_to for_hires_path, :notice => "Updated for hire entry."
    else
      render :action => :edit
    end
  end

  def destroy
    @for_hire = current_user.for_hire
    if @for_hire && @for_hire.destroy
      flash[:notice] = "Deleted your for hire entry."
    else
      flash[:alert] = "Error deleting your for hire profile."
    end

    redirect_to for_hires_path
  end


  private

    def bounce_foreign_access
      if params[:id]
        session[:uid] = nil
        redirect_to root_path
      end
    end
end

app/views/for_hires/_for_hire.html.haml
%li
  .for_hire
    %h1= for_hire.title
    %p= mup for_hire.blurb
    .author
      - if for_hire.user.gravatar_email.present?
        .gravatar{ :style => "background-image: url(#{gravatar_url(for_hire.user.gravatar_email, :size => 35)})" }
      = mail_to for_hire.email, "Email", :encode => 'javascript'
    - if i_am(for_hire.user) || (current_user && current_user.admin?)
      %br/
      .control
        [ #{link_to "Edit", edit_for_hire_path} #{link_to "Delete", :for_hire, :method => :delete, :confirm => 'Are you sure?'} ]

app/views/for_hires/_for_hire_form_fields.haml
%fieldset
  %label Title
  = f.text_field "title"
  %br/

  %label Email
  = text_field "for_hire", "email"
  %br/

  %label Blurb
  = text_area "for_hire", "blurb"
  %br/

  .submit
    = submit_tag "Save"

app/views/for_hires/_form.html.haml
= form_for @for_hire, :url => for_hire_path do |f| 
  = f.error_messages
  %fieldset
    = f.label :title
    = f.text_field :title
    %br/
    = f.label :email
    = f.text_field :email
    %br/
    = f.label :blurb
    = f.text_area :blurb, :rows => 20, :cols => 37
    %br/
    .submit
      = f.submit f.object.new_record? ? 'Create Entry' : 'Edit Entry'

app/views/for_hires/edit.html.haml
.introduction
  %h2 Edit Your "For Hire" Entry

  %p [#{ link_to 'Markdown', 'http://daringfireball.net/projects/markdown/syntax' } accepted]

.form= render 'form'

app/views/for_hires/index.html.haml
.introduction
  %h1 Available For Hire

  %p If you're looking for some local Ruby talent to help with your project, or just hang around drinking beers all day, you could do worse than starting with this list.

  - if current_user
    %br
    - unless current_user.for_hire
      %p If you are a Ruby developer, #{ link_to 'add your listing', new_for_hire_path }.
    - else
      %p You already have a "For Hire" entry.  You may edit it #{link_to 'here', :action => 'edit'}.

.hires
  %ul
    = render @for_hires

app/views/for_hires/new.html.haml
.introduction
  %h2 Create Your "For Hire" Entry

  %p [#{ link_to 'Markdown', 'http://daringfireball.net/projects/markdown/syntax' } accepted]

.form= render 'form'