config/routes.rb
RubyMnWebsite::Application.routes.draw do
  resources :users do
    get 'page/:page', :action => :index, :on => :collection

    member do
      get :login
    end

    new do
      get  :validate
      get  :forgot_password
      post :reset
      get  :change_password
      post :set_password
    end
  end

  resource :for_hire
  match '/for_hires' => 'for_hires#index', :as => :for_hires

  resources :events do
    member do
      delete :admdestroy
      #put    :approve
    end

    collection do
      get :user_index
    end
  end

  resources :openings do
    get 'page/:page', :action => :index, :on => :collection
  end
  resources :projects
  resource :session
  resources :sponsors

  # map.admin '/admin/:action/:id', :controller => 'admin'
  #match '/admin/:action/:id' => 'admin', :as => :admin

  put '/admin/events/:id/approve' => 'admin#approve', :as => :admin_approve_event
  match '/admin'        => 'admin#index',   :as => :admin_index

  root :to => 'welcome#index'
end

app/views/shared/_flash_messages.html.haml
- if flash[:notice]
  .notice= flash[:notice]
- if flash[:alert]
  .error= flash[:alert]

app/views/shared/_google_analytics.html.haml
- if Rails.env.production?
  %script{ :src => "http://www.google-analytics.com/urchin.js", :type => "text/javascript" }
  :javascript
    _uacct = "UA-755912-2";
    urchinTracker();

app/views/shared/_logged_in_as.html.haml
#logged_in_as
  #logged_in_text
    
  .user_login
    - if current_user.gravatar_email.present?
      .gravatar{ :style => "background-image: url(#{gravatar_url(current_user.gravatar_email, :size => 18)})" }
    .login= current_user.login

app/views/shared/_navigation.html.haml
%ul
  %li= link_to "<strong>Home</strong><p>Welcome and Events</p>".html_safe,       root_path,           :class => ('selected' if current_page? root_path)
  %li= link_to "<strong>Members</strong><p>People and Projects</p>".html_safe,   projects_path,       :class => ('selected' if current_page? projects_path)
  %li= link_to "<strong>For Hire</strong><p>Developers for hire</p>".html_safe,  for_hires_path,      :class => ('selected' if current_page? for_hires_path)
  %li= link_to "<strong>Need Help?</strong><p>Seeking developers</p>".html_safe, openings_path,       :class => ('selected' if current_page? openings_path)
  %li= link_to "<strong>Sponsors</strong><p>Community Supporters</p>".html_safe, sponsors_path,       :class => ('selected' if current_page? sponsors_path)

app/views/shared/_sidebar.html.haml
= render 'shared/logged_in_as' if logged_in?
#navbar
  #links
    %ul
      - if current_user
        %li.members_list
          = link_to "Member List", users_path
          #users_size{ :title => 'Number of members' }= User.verified.count
        %li= link_to "Help Wanted", openings_path
        %li= link_to "My Events", user_index_events_path
        %li= link_to 'Edit My Account', edit_user_path(current_user)
        - if current_user.admin?
          %li= link_to "Admin", admin_index_path
        %li= link_to "Logout", session_path, :method => 'delete'
      - else
        %li= link_to "Join", new_user_path
        %li= link_to "Login", new_session_path
  #register
    .next-meeting
      %h3 Register now for the next meeting
      <iframe width="200" height="420" src="http://meetu.ps/2Rx1rR" frameborder="0"></iframe>

  #email_list
    %p
      #{ link_to "Our mailing list is hosted on Google Groups", 'http://groups.google.com/group/rubymn?hl=en', :title => 'Visit the Ruby.MN Google Group', :alt => 'Visit the Ruby.MN Google Group' } and is the primary way to discuss Ruby with our members.
    = form_tag "http://groups.google.com/group/rubymn/boxsubscribe", :id => 'subscribe' do
      %fieldset
        = hidden_field_tag :hl, "en"
        %div
          = label_tag :email, 'Subscribe By Email'
          %br/
          = text_field_tag :email
        %div
          = submit_tag "Subscribe"
  #twitter
    %h4
      = link_to 'http://twitter.com/rubyMN' do
        = image_tag 'rumlogo.png', :size => '40x40', :alt => 'RubyMN', :id => 'rubymn_logo_twitter'
        Recent Tweets From @RubyMN
    #tweets
      <a class="twitter-timeline" href="https://twitter.com/RubyMN" data-widget-id="520923539092680704">Tweets by @RubyMN</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>