config/routes.rb
RubyMnWebsite::Application.routes.draw do
  resources :users do
    get 'page/:page', :action => :index, :on => :collection

    member do
      get :login
    end

    new do
      get  :validate
      get  :forgot_password
      post :reset
      get  :change_password
      post :set_password
    end
  end

  resource :for_hire
  match '/for_hires' => 'for_hires#index', :as => :for_hires

  resources :events do
    member do
      delete :admdestroy
      #put    :approve
    end

    collection do
      get :user_index
    end
  end

  resources :openings do
    get 'page/:page', :action => :index, :on => :collection
  end
  resources :projects
  resource :session
  resources :sponsors

  # map.admin '/admin/:action/:id', :controller => 'admin'
  #match '/admin/:action/:id' => 'admin', :as => :admin

  put '/admin/events/:id/approve' => 'admin#approve', :as => :admin_approve_event
  match '/admin'        => 'admin#index',   :as => :admin_index

  root :to => 'welcome#index'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id             :integer          not null, primary key
#  created_at     :datetime
#  scheduled_time :datetime
#  headline       :string(200)      default(""), not null
#  body           :text             not null
#  user_id        :integer          default(0), not null
#  approved       :boolean          default(FALSE)
#

class Event < ActiveRecord::Base
  # Associations
  belongs_to :user

  # Validations
  validates :headline,       :presence => true
  validates :scheduled_time, :presence => true
  validates :body,           :presence => true
  validates :user_id,        :presence => true

  # Scopes
  scope :approved, includes(:user).where(:approved => true).limit(5)
  scope :unapproved, where(:approved => false)
  scope :order_scheduled_time_desc, order('scheduled_time desc')

  def formatted_scheduled_time
    self.scheduled_time.try(:to_s, :jquery_datepicker)
  end

  def formatted_scheduled_time=(unformatted_time)
    self.scheduled_time = Chronic.parse(unformatted_time.to_s)
  end

  def unapproved?
    !approved?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :login_required
  before_filter :admin_required, :only => :show

  def index
    if current_user.admin?
      @events = Event.includes(:user).order_scheduled_time_desc
    else
      @user   = current_user
      @events = @user.events
    end
  end

  def user_index
    if logged_in? 
      if current_user.admin? && params[:user_id]
        @user = User.find(params[:user_id])
      else
        @user = current_user
      end

      @events = @user.events.order_scheduled_time_desc
      render :template => 'events/index'
    else
      bounce
    end
  end

  def create
    @event = current_user.events.build(params[:event])

    if @event.save
      redirect_to user_index_events_path
      Notifier.notify_event(@event).deliver
    else
      render :action => :new
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to user_index_events_path, :notice => 'Event Updated'
    else
      render :action => :edit
    end
  end

  def new
    @event = Event.new :formatted_scheduled_time => Time.now
  end

  def destroy
    if current_user && current_user.admin?
      @event = Event.find(params[:id])
      redirect_path = admin_index_path
    else
      @event = current_user.events.find(params[:id])
      redirect_path = user_index_events_path
    end

    @event.destroy
    redirect_to redirect_path, :notice => 'Event Deleted'
  end
  

  def edit
    if current_user && current_user.admin?
      @event = Event.find(params[:id])
    else
      @event = current_user.events.find(params[:id])
    end
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/views/events/_event.haml
%li
  .event
    - if event.scheduled_time
      %h3= event.headline
      .time= event.scheduled_time.to_s(:short)
    - if current_user and (event.user == current_user || current_user.admin?)
      = link_to "Delete", event_path(event), :method=>:delete
      = link_to "Edit", edit_event_path(event)
    - if current_user and current_user.admin?
      = link_to "Details", event_path(event)
    %h4
      - if event.user == current_user
        = event.approved? ? "Approved" : "Not Approved Yet"
    .content
      = mup(event.body)

app/views/events/_event.html.haml
- show_approved ||= false
%li
  .event
    - if event.scheduled_time
      %h3= event.headline
      .time= event.scheduled_time.to_s(:short_meridian)
      [
      - if (current_user && current_user.admin?) && event.unapproved?
        #{ link_to "Approve", admin_approve_event_path(event), :method => :put }
      - if current_user and (event.user == current_user || current_user.admin?)
        #{ link_to "Edit", edit_event_path(event) }
        #{ link_to "Delete", event_path(event), :method => :delete, :confirm => 'Are you sure?' }
      = link_to "Details", event_path(event)
      .register_for_event{:style => 'display: inline'}
        Attend!
      ]
    - if show_approved
      %h4= event.approved? ? "Approved" : "Not Approved Yet" if event.user == current_user
    .content
      = mup event.body
    .event_registration_form.form{:style => 'display: none' }
      - @event = event
      - @event_registration = EventRegistration.new
      - @event.amenities.each do |a|
        - @event_registration.amenities_events.build(:amenity_id => a.id, :event_id => @event.id)
      = render 'event_registrations/form'

app/views/events/_form.html.haml
- content_for :after_stylesheets do
  = stylesheet_link_tag 'jquery-ui-1.8.16'
- content_for :after_javascripts do
  = javascript_include_tag 'events_form'

= form_for @event, :html => { :class => 'event_form' } do |f|
  = f.error_messages
  %fieldset
    = f.label :headline
    = f.text_field :headline
    %br/
    = f.label :formatted_scheduled_time, 'Time &amp; Date'.html_safe
    = f.text_field :formatted_scheduled_time, :class => 'datepicker'
    %br/
    = f.label :body, 'Details'
    = f.text_area :body

    - if current_user.admin?
      %br/
      .checkbox_input
        = f.check_box :approved
        = f.label :approved

    .submit
      = submit_tag f.object.new_record? ? "Submit Event" : "Update Event"

app/views/events/edit.html.haml
.introduction
  %h2 Edit Event

  - h @event.body.try(:gsub!,/\r\n/,"\r")

.form= render 'form'

app/views/events/event_form.haml
.form
  - form_for :event, :url=>user_events_path do |f|
    %fieldset
      %legend
        New Event
      %label
        Headline 
      = f.text_field  :headline
      %br/
      %label
        Time &amp; Date:
      = f.datetime_select  :scheduled_time
      %br/
      (That's 24 hour time bub.)
      %br/
      %label
        Details
      = f.text_area  "body"
      .submit
        =submit_tag

app/views/events/index.html.haml
.introduction
  %h1 Events
  %p You want to #{ link_to 'create', new_event_path } an event?
  %br/
  %h2.your_events Your events
%ul.events= render @events
%p.note
  %strong Note:
  Events must be approved by an administrator before they appear on the front page. If this is a commercial #{ content_tag :em, 'event' }, it will probably be denied, unless you contact #{ mail_to ::ADMIN_ADDRESS, 'the administrators' } first.

app/views/events/new.html.haml
.introduction
  %h2 New Event

.form= render 'form'

app/views/events/show.html.haml
.introduction
  %h1 Event Detail
  %h2
    = h @event.headline
    %br/
    = @event.scheduled_time.to_s(:long_meridian)

  %p
    Created by:
    = mail_to(@event.user.email, h(@event.user.login), :encode => 'javascript')
    %br/
    Created at: 
    = @event.created_at
  %p
    = mup h(@event.body)